# Model arguments
model_name_or_path: bytedance-research/UI-TARS-7B-DPO
model_revision: main
torch_dtype: bfloat16

# Data training arguments
dataset_name: boot_osworld_vscode_p0
dataset_configs:
- all
preprocessing_num_workers: 8

# SFT trainer config
bf16: true
do_eval: true
eval_strategy: "no"
gradient_accumulation_steps: 4
gradient_checkpointing: true
gradient_checkpointing_kwargs:
  use_reentrant: false
hub_model_id: Qwen2-VL-7B-Instruct-SFT
hub_strategy: every_save
learning_rate: 2.0e-05
log_level: info
logging_steps: 5
logging_strategy: steps
lr_scheduler_type: cosine
packing: true
max_seq_length: 16384
max_steps: -1
num_train_epochs: 4
output_dir: data/UI-TARS-7B-DPO-VSCode-SFT_fixbox_fixresize_p0
overwrite_output_dir: true
per_device_eval_batch_size: 1
per_device_train_batch_size: 2
push_to_hub: false
report_to:
- wandb
save_strategy: "steps"
save_steps: 50
seed: 42
warmup_ratio: 0.1
